### ISSUE TITLE
Hdf5 flags not set properly for fortran?

### ISSUE THREAD

**Issue by rjfarmer** [amusecode/amuse#753]
**Describe the bug**
I don't think HDF5_LIBS and HDF5_FLAGS (as of f873340a so after @rieder 's update to aclocal.m4 in 162f3bc3) are set correctly for compiling fortran codes (but are set correctly, i think, for C)

**To Reproduce**
./configure
Check config.mk, i get:

````
HDF5_FLAGS=-I/usr/include
HDF5_LIBS= -L/usr/lib64/openmpi/lib -lhdf5_hl -lhdf5  -lhdf5_hl -lsz -lz -ldl -lm
````
However, /usr/include does not include hdf5.mod, as that's in /usr/lib64/gfortran/modules on my machine. 
What worked in the past for me is:

````
HDF5_FLAGS = -I/usr/lib64/gfortran/modules/
HDF5_LIBS = -L/usr/lib64 -lhdf5_fortran -lhdf5 -lz
````

Searching my system for hdf5.mod:
````
find /usr -name 'hdf5.mod' 2>/dev/null
/usr/lib64/gfortran/modules/hdf5.mod
/usr/lib64/gfortran/modules/openmpi/hdf5.mod
````

So HDF5_FLAGS should definitely be going to somewhere in /usr/lib64 not /usr/include (though that's where the hdf5 headers files are so that's why i think its setting things for C). HDF5_LIBS is also missing the -lhdf5_fortran link

I'm on fedora 33.

**Comment by ipelupessy** [comment]
thanks, the hdf5 fortran flags HDF5_FFLAGS and HDF5_FLIBS are added now ( https://github.com/amusecode/amuse/commit/d2dcc1ad83a6628ef1c54a6aac1b32c4f9cc970e ). It should work with these

**Comment by ipelupessy** [comment]
fixed by https://github.com/amusecode/amuse/commit/d2dcc1ad83a6628ef1c54a6aac1b32c4f9cc970e

**Comment by rjfarmer** [comment]
Thanks, not quite there yet though. The new options return this:

````
HDF5_FFLAGS= -I/usr/include/openmpi-x86_64 -L/usr/lib64/openmpi/lib -I/usr/lib64/openmpi/lib
HDF5_FLIBS= -L/usr/lib64/openmpi/lib  -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5 -lhdf5hl_fortran -lhdf5_hl -lsz -lz -ldl -lm
````

So the FFLAGS is still missing the include on /usr/lib64/gfortran/modules which my system needs. Looking at 162f3bc line 291 it looks like the include flags are coming from parsing the output of h5pfc -show:

````
h5pfc -show
mpif90 -I/usr/include/openmpi-x86_64 -L/usr/lib64/openmpi/lib -lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5
````

Looking at the longer h5pfc -showconfig (and just the fortran flags):

````
Fortran Flags: -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules -I/usr/lib64/gfortran/modules/openmpi
````

which does now show the correct -I/usr/lib64/gfortran/modules/openmpi flag. So it seems -show does not show the correct info, but -showconfig does.

Could be  bug in the h5pfc shipped with fedora? Or maybe we need a different aclocal macro?

**Comment by ipelupessy** [comment]
ouch, in this case I tend to consider this indeed an issue which needs to be patched upstream (either h5pfc or the m4 macro) or in the fedora distribution. The m4 macro comes from the gnu archive btw. A workaround could be  to set a FCFLAGS=-I/usr/lib64/gfortran/modules/openmpi

**Comment by rieder** [comment]
That workaround path would not be correct on macOS...

**Comment by ipelupessy** [comment]
well, you would only need it on fedora..(hopefully: I haven't tested on macOS)

**Comment by rjfarmer** [comment]
So in theory adding this to aclocal.m4 at line 307 would add the extra paths we need:

````
            for arg in `$H5FC -showconfig | grep 'Fortran Flags'`
            do
              case "$arg" in #(
                -I*) echo $HDF5_FFLAGS | $GREP -e "$arg" >/dev/null \
                      || HDF5_FFLAGS="$HDF5_FFLAGS $arg"
                  ;;#(
                -L*) echo $HDF5_FFLAGS | $GREP -e "$arg" >/dev/null \
                      || HDF5_FFLAGS="$HDF5_FFLAGS $arg"
                     dnl HDF5 installs .mod files in with libraries,
                     dnl but some compilers need to find them with -I
                     echo $HDF5_FFLAGS | $GREP -e "-I${arg#-L}" >/dev/null \
                      || HDF5_FFLAGS="$HDF5_FFLAGS -I${arg#-L}"
                  ;;
              esac
            done
```

Though i'm struggling with autotools to work out how to get ./configure to see the changes in aclocal.m4

**Comment by ipelupessy** [comment]
ok, i  think this could be added to m4/m4_ax_lib_hdf5.m4 (after which we can regenerate aclocal.m4 and configure), though hopefully this -showconfig option is always present (and should it replace the flags derived from the -show option?)

**Comment by rjfarmer** [comment]
aclocal.m4 uses -showconfig earlier when sorting out the C flags for hdf5 so that should be fine

**Comment by rjfarmer** [comment]
No i dont think it replaces the ones form -show, so what i posted just appends to the flags. As -show gets us the right flags for the library linking while -showconfig is getting us the right flags for including the mod files.

**Comment by ipelupessy** [comment]
I have added it

**Comment by rjfarmer** [comment]
Thats working now, thanks
